config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  scope module: :web do
    root 'homepage#index'

    resources :articles, only: %i[index show]

    namespace :admin do
      root 'articles#index'
      resources :articles
    end

  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user

  has_one_attached :photo

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 50 }
  validates :photo,
            size: { less_than_or_equal_to: 5.megabyte },
            content_type: %i[png]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def page
    params.fetch(:page, 1)
  end

  def per_page
    params.fetch(:per_page, 10)
  end
end

app/controllers/web/admin/articles_controller.rb
# frozen_string_literal: true

class Web::Admin::ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = Article.order(created_at: :desc)
                       .page(page)
                       .per(per_page)
  end

  def show
    @article = Article.find_by(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = current_user.articles.build article_params

    if @article.save
      redirect_to admin_root_path, notice: t('.success')
    else
      render :new
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update article_params
      redirect_to @article, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :exclusion_date, :photo)
  end
end

app/controllers/web/articles_controller.rb
# frozen_string_literal: true

class Web::ArticlesController < ApplicationController
  def index
    @time_at = Time.zone.now
    @articles = Article.where('exclusion_date < ?', @time_at)
                       .order(created_at: :desc)
                       .page(page)
                       .per(per_page)
  end

  def show
    @article = Article.find_by(params[:id])
  end
end

app/controllers/web/homepage_controller.rb
# frozen_string_literal: true

class Web::HomepageController < ApplicationController
  def index
    @time_at = Time.zone.now
    @articles = Article.where('exclusion_date < ?', @time_at)
                       .order(created_at: :desc)
                       .limit(3)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/web/admin/articles_helper.rb
# frozen_string_literal: true

module Web::Admin::ArticlesHelper
end

app/helpers/web/articles_helper.rb
# frozen_string_literal: true

module Web::ArticlesHelper
end

app/helpers/web/homepage_helper.rb
# frozen_string_literal: true

module Web::HomepageHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    title Быстрые Отчеты | Блог

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body.d-flex.flex-column.h-100
    = render 'shared/nav'
    = render 'shared/flash'
    main.mt-sm-2.mb-2.pb-2
      .container
        = yield

app/views/shared/_flash.html.slim
- if flash[:notice]
  .container.my-2
    - flash.each do |_, msg|
      .alert.alert-info
        = msg

- if flash[:alert]
  .container.my-2
    - flash.each do |_, msg|
      .alert.alert-danger
        = msg

app/views/shared/_nav.html.slim
.container
  .container
    header.d-flex.flex-wrap.justify-content-center.py-3.mb-4.border-bottom
      - if signed_in?
        = link_to articles_path, class: 'd-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none' do
          span.fs-4 = t(:title)
        ul.nav.nav-pills
          = link_to t('.create_article'), new_admin_article_path, class: 'nav-link link-dark'
          = link_to t('.edit_all'), admin_articles_path, class: 'nav-link link-dark'
          = link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link link-dark'
      - else
        = link_to root_path, class: 'd-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none' do
          span.fs-4 = t(:title)
        ul.nav.nav-pills
          = link_to t('.articles'), articles_path, class: 'nav-link link-dark'
          = link_to t('.sign_in'), new_user_session_path, class: 'nav-link link-dark'

app/views/web/admin/articles/_form.html.slim
= simple_form_for [:admin, @article] do |f|
  .mb-3
    = f.input :title, class: 'form-group mb-3'
  .mb-3
    = f.input :body, input_html: { rows: 10 }, class: 'form-group mb-3'
  .mb-3
    = f.input :exclusion_date, as: :datetime
  .form-group.mb-3
    = f.file_field :photo, class: 'form-control'
  .mt-2
    = f.button :submit, class: 'btn-outline-primary me-2'
    = link_to t('back'), :back, class: 'btn btn-outline-secondary'

app/views/web/admin/articles/edit.html.slim
.row.gx-4.gx-lg-5.justify-content-center
  .col-sm-9

    = render 'form'

app/views/web/admin/articles/index.html.slim
table.table
  thead
    tr
      th = t('.id')
      th = t('.title')
      th = t('.edit')
      th = t('.delete')
  tbody
    - @articles.each do |article|
      tr
        td = link_to article.id, edit_admin_article_path(article)
        td = article.title
        td = link_to t('.edit'), edit_admin_article_path(article)
        td = link_to t('.delete'), admin_article_path(article), method: :delete, data: {confirm: 'Are you sure?'}

        
  tfoot
    tr
      td colspan=6
        = paginate @articles

app/views/web/admin/articles/new.html.slim
h1 = t('.title')

= render 'form', post: @post

app/views/web/admin/articles/show.html.slim
h2 = @article.title
.d-flex.justify-content-between.mb-3.mt-1
  .post-section
    span = time_ago_in_words @article.created_at
p = simple_format @article.body

app/views/web/articles/_article.html.slim
.col-lg-6
  .card.h-100.article
    = link_to article_path(article), class: 'text-decoration-none link-secondary h-100'
      .row.h-100
        .col-md-4.h-100
          - if article.photo_attachment
            = image_tag(article.photo, class: 'img-fluid rounded-start')
          - else
            .no-img.bg-secondary
              i.bi.bi-card-image.text-light
        .col-md-8
          .card-body.d-flex.flex-column.justify-content-between.h-100
            h5.card-title = article.title
            hr
            p.card-text.text-truncate.flex-grow-1 = article.body
            p.card-text
              hr
              small.text-muted
                |
              small.text-muted #{t('.created_at')}: #{l(article.created_at)}

app/views/web/articles/index.html.slim
.row.row-cols-1.g-4
  = render @articles

= paginate @articles

app/views/web/articles/show.html.slim
h2 = @article.title
.d-flex.justify-content-between.mb-3.mt-1
  .post-section
    span = time_ago_in_words @article.created_at
p = simple_format @article.body

app/views/web/homepage/index.html.slim
- @articles.each do |article|
  .card.mb-3
    .card-img-top = article.photo
    .card-header = link_to article.title, article
    .card-body.card-text = article.body.truncate_words(18)
    .card-footer
      span.me-2
        = time_ago_in_words article.created_at
        